DROP DATABASE IF EXISTS PERFDB;
DROP USER IF EXISTS PERFUSER;

CREATE DATABASE BOOKDB WITH ENCODING 'UTF8'; 
CREATE USER BOOKUSER WITH PASSWORD '12345678';
GRANT ALL PRIVILEGES ON DATABASE BOOKDB to BOOKUSER;
